name: CI

on:
  - push
  - pull_request

jobs:
  backend-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: make setup-backend

      - name: Test with tox
        run: make test-backend

  frontend-test:
    runs-on: ${{ matrix.os }}
    needs: [backend-test]
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: Install dependencies
        run: make setup-frontend

      - name: Test with vitest
        run: make test-frontend
